// Phase 5.4 — Enterprise API Standardization. Every backend endpoint now
// lives under /api/v1 (see backend/app/main.py — every router is mounted
// both at its legacy bare prefix for backward compatibility AND under
// /api/v1 as the official, standardized surface). All values here use the
// /api/v1 form; the bare/legacy paths still work on the backend but are no
// longer called from the frontend.
export const ADMIN_ENDPOINTS = {
  languages: "/api/v1/languages/",
  levels: "/api/v1/courses/",
  modules: "/api/v1/modules",
  lessons: "/api/v1/lessons",
  lessonsByModule: (moduleId: string) => `/api/v1/lessons/module/${moduleId}`,
  lessonsContentStatus: (moduleId: string) => `/api/v1/lessons/module/${moduleId}/content-status`,
  videos: "/api/v1/admin/videos",
  videosByLesson: (lessonId: string) => `/api/v1/admin/videos?lesson_id=${lessonId}`,
  listenings: "/api/v1/listenings",
  writings: "/api/v1/writings",
  speakings: "/api/v1/speakings",
  adminBooks: "/api/v1/admin/books",
  adminTeacherAssignments: "/api/v1/admin/teacher-assignments",
  adminTeacherAssignmentCandidates: "/api/v1/admin/teacher-assignments/candidates",
  examProviders: "/api/v1/exam-providers",
  exams: "/api/v1/exams",
  mediaLibrary: "/api/v1/media-library/",
  mediaLibraryUpload: "/api/v1/media-library/upload",
  adminUsers: "/api/v1/admin/users",
  adminVizuPay: "/api/v1/admin/vizu-pay",
  paymentsPaginated: "/api/v1/payments/paginated",

  certificates: "/api/v1/certificates",
  adminDashboard: "/api/v1/admin/dashboard/overview",

  // Mock Exam System (Phase 4)
  mockExamProviders: "/api/v1/mock-exam/providers",
  mockExamLevels: "/api/v1/mock-exam/levels",
  mockExamModelTests: "/api/v1/mock-exam/model-tests",
  mockExamModelTestScore: (modelTestId: string) => `/api/v1/mock-exam/model-tests/${modelTestId}/score`,
  mockExamKompetenzen: "/api/v1/mock-exam/kompetenzen",
  mockExamTeile: "/api/v1/mock-exam/teile",
  mockExamListeningContent: "/api/v1/mock-exam/listening-content",
  mockExamListeningContentByTeil: (teilId: string) => `/api/v1/mock-exam/teile/${teilId}/listening-content`,
  mockExamWritingTasks: "/api/v1/mock-exam/writing-tasks",
  mockExamWritingTaskByTeil: (teilId: string) => `/api/v1/mock-exam/teile/${teilId}/writing-task`,
  mockExamSpeakingTasks: "/api/v1/mock-exam/speaking-tasks",
  mockExamSpeakingTaskByTeil: (teilId: string) => `/api/v1/mock-exam/teile/${teilId}/speaking-task`,
  mockExamDashboardSummary: "/api/v1/mock-exam/dashboard-summary",
  mockExamModelTestAnalytics: (modelTestId: string) => `/api/v1/mock-exam/model-tests/${modelTestId}/analytics`,
  mockExamProviderAnalytics: (providerId: string) => `/api/v1/mock-exam/providers/${providerId}/analytics`,

  // VIZU-Multilevel Admin Dashboard
  vizuMultilevelOverview: "/api/v1/admin/vizu-multilevel/overview",
  vizuMultilevelActivity: "/api/v1/admin/vizu-multilevel/activity",
  vizuMultilevelLevelAnalytics: "/api/v1/admin/vizu-multilevel/level-analytics",
  vizuMultilevelAnalytics: "/api/v1/admin/vizu-multilevel/analytics",
  vizuMultilevelAttempts: "/api/v1/admin/vizu-multilevel/attempts",
  vizuMultilevelStudents: "/api/v1/admin/vizu-multilevel/students",
  vizuMultilevelAttemptDetail: (attemptId: string) => `/api/v1/admin/vizu-multilevel/attempts/${attemptId}`,
  vizuMultilevelLesenContent: "/api/v1/admin/vizu-multilevel/lesen-content",
  vizuMultilevelLesenContentImportJson: "/api/v1/admin/vizu-multilevel/lesen-content/import-json",
  vizuMultilevelLesenContentImportCsv: "/api/v1/admin/vizu-multilevel/lesen-content/import-csv",
  vizuMultilevelHoerenContent: "/api/v1/admin/vizu-multilevel/hoeren-content",
  vizuMultilevelHoerenContentImportCsv: "/api/v1/admin/vizu-multilevel/hoeren-content/import-csv",
  vizuMultilevelSchreibenContent: "/api/v1/admin/vizu-multilevel/schreiben-content",
  vizuMultilevelSchreibenContentDetail: (taskId: string) => `/api/v1/admin/vizu-multilevel/schreiben-content/${taskId}`,
  vizuMultilevelSprechenContent: "/api/v1/admin/vizu-multilevel/sprechen-content",
  vizuMultilevelSprechenContentDetail: (taskId: string) => `/api/v1/admin/vizu-multilevel/sprechen-content/${taskId}`,
  vizuMultilevelAttemptSprechen: (attemptId: string) => `/api/v1/admin/vizu-multilevel/attempts/${attemptId}/sprechen`,
  vizuMultilevelAttemptCertificate: (attemptId: string) => `/api/v1/admin/vizu-multilevel/attempts/${attemptId}/certificate`,
  vizuMultilevelAttemptCertificatePdf: (attemptId: string) => `/api/v1/admin/vizu-multilevel/attempts/${attemptId}/certificate/pdf`,
  vizuMultilevelAttemptSprechenAudio: (attemptId: string, submissionId: string) =>
    `/api/v1/admin/vizu-multilevel/attempts/${attemptId}/sprechen/submissions/${submissionId}/audio`,
  vizuMultilevelContentTasks: (skill: "lesen" | "hoeren") => `/api/v1/admin/vizu-multilevel/content/${skill}/tasks`,
  vizuMultilevelContentTask: (taskId: string) => `/api/v1/admin/vizu-multilevel/content/tasks/${taskId}`,
  vizuMultilevelContentTaskQuestions: (taskId: string) => `/api/v1/admin/vizu-multilevel/content/tasks/${taskId}/questions`,
  vizuMultilevelContentQuestion: (questionId: string) => `/api/v1/admin/vizu-multilevel/content/questions/${questionId}`,
  vizuMultilevelStatistics: "/api/v1/admin/vizu-multilevel/statistics",
  vizuMultilevelHoerenDiagnostics: "/api/v1/admin/vizu-multilevel/hoeren/diagnostics",
  vizuMultilevelHoerenAudio: "/api/v1/admin/vizu-multilevel/hoeren/audio",
  vizuMultilevelHoerenAudioDetail: (audioId: string) => `/api/v1/admin/vizu-multilevel/hoeren/audio/${audioId}`,
  vizuMultilevelHoerenContentImportJson: "/api/v1/admin/vizu-multilevel/hoeren-content/import-json",
} as const;
