// Exact backend paths — verified against each router's route decorators
// (trailing-slash usage is inconsistent across the backend, so every value
// here was checked against source, not assumed).
export const ADMIN_ENDPOINTS = {
  languages: "/languages/",
  levels: "/courses/",
  modules: "/modules",
  lessons: "/lessons",
  lessonsByModule: (moduleId: string) => `/lessons/module/${moduleId}`,
  videos: "/admin/videos",
  videosByLesson: (lessonId: string) => `/admin/videos?lesson_id=${lessonId}`,
  vocabularies: "/vocabularies/",
  grammar: "/grammars",
  readings: "/readings/",
  readingQuestions: "/reading-questions",
  readingOptions: "/reading-options",
  listenings: "/listenings",
  writings: "/writings",
  speakings: "/speakings",
  quizzes: "/quizzes",
  quizQuestions: "/quiz-questions",
  quizOptions: "/quiz-options",
  homeworks: "/homeworks",
  examProviders: "/exam-providers",
  exams: "/exams",
  mediaLibrary: "/media-library/",
  mediaLibraryUpload: "/media-library/upload",
  adminUsers: "/admin/users",
  adminVizuPay: "/admin/vizu-pay",
  certificates: "/api/v1/certificates",
  adminDashboard: "/admin/dashboard/overview",

  // Mock Exam System (Phase 4)
  mockExamProviders: "/mock-exam/providers",
  mockExamLevels: "/mock-exam/levels",
  mockExamModelTests: "/mock-exam/model-tests",
  mockExamModelTestScore: (modelTestId: string) => `/mock-exam/model-tests/${modelTestId}/score`,
  mockExamKompetenzen: "/mock-exam/kompetenzen",
  mockExamTeile: "/mock-exam/teile",
  mockExamReadingContent: "/mock-exam/reading-content",
  mockExamReadingContentByTeil: (teilId: string) => `/mock-exam/teile/${teilId}/reading-content`,
  mockExamListeningContent: "/mock-exam/listening-content",
  mockExamListeningContentByTeil: (teilId: string) => `/mock-exam/teile/${teilId}/listening-content`,
  mockExamWritingTasks: "/mock-exam/writing-tasks",
  mockExamWritingTaskByTeil: (teilId: string) => `/mock-exam/teile/${teilId}/writing-task`,
  mockExamSpeakingTasks: "/mock-exam/speaking-tasks",
  mockExamSpeakingTaskByTeil: (teilId: string) => `/mock-exam/teile/${teilId}/speaking-task`,
  mockExamQuestions: "/mock-exam/questions",
  mockExamQuestionDuplicate: (questionId: string) => `/mock-exam/questions/${questionId}/duplicate`,
  mockExamQuestionMove: (questionId: string) => `/mock-exam/questions/${questionId}/move`,
  mockExamQuestionOptions: "/mock-exam/question-options",
  mockExamAttempts: "/mock-exam/attempts",
  mockExamAttemptFinalize: (attemptId: string) => `/mock-exam/attempts/${attemptId}/finalize`,
  mockExamWritingSubmissions: "/mock-exam/writing-submissions",
  mockExamWritingSubmissionAiEvaluate: (id: string) => `/mock-exam/writing-submissions/${id}/ai-evaluate`,
  mockExamWritingSubmissionReview: (id: string) => `/mock-exam/writing-submissions/${id}/teacher-review`,
  mockExamSpeakingSubmissions: "/mock-exam/speaking-submissions",
  mockExamSpeakingSubmissionAiEvaluate: (id: string) => `/mock-exam/speaking-submissions/${id}/ai-evaluate`,
  mockExamSpeakingSubmissionReview: (id: string) => `/mock-exam/speaking-submissions/${id}/teacher-review`,
  mockExamDashboardSummary: "/mock-exam/dashboard-summary",
  mockExamModelTestAnalytics: (modelTestId: string) => `/mock-exam/model-tests/${modelTestId}/analytics`,
  mockExamProviderAnalytics: (providerId: string) => `/mock-exam/providers/${providerId}/analytics`,
} as const;
