"""create_student_progress_table

Revision ID: 0e1486b81d78
Revises: 91184abc44ec
Create Date: 2026-07-12 17:07:17.208905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1486b81d78'
down_revision: Union[str, Sequence[str], None] = '91184abc44ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('video_completed', sa.Boolean(), nullable=False),
    sa.Column('grammar_completed', sa.Boolean(), nullable=False),
    sa.Column('reading_completed', sa.Boolean(), nullable=False),
    sa.Column('listening_completed', sa.Boolean(), nullable=False),
    sa.Column('writing_completed', sa.Boolean(), nullable=False),
    sa.Column('speaking_completed', sa.Boolean(), nullable=False),
    sa.Column('quiz_completed', sa.Boolean(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('lesson_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_progress_lesson_id'), 'student_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_student_progress_user_id'), 'student_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_progress_user_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_lesson_id'), table_name='student_progress')
    op.drop_table('student_progress')
    # ### end Alembic commands ###
