"""create_student_writings_table

Revision ID: 55de3fa5d10b
Revises: 0e1486b81d78
Create Date: 2026-07-12 20:28:59.948551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55de3fa5d10b'
down_revision: Union[str, Sequence[str], None] = '0e1486b81d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_writings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('writing_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('grammar_score', sa.Integer(), nullable=False),
    sa.Column('vocabulary_score', sa.Integer(), nullable=False),
    sa.Column('coherence_score', sa.Integer(), nullable=False),
    sa.Column('task_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['writing_id'], ['writings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_writings_user_id'), 'student_writings', ['user_id'], unique=False)
    op.create_index(op.f('ix_student_writings_writing_id'), 'student_writings', ['writing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_writings_writing_id'), table_name='student_writings')
    op.drop_index(op.f('ix_student_writings_user_id'), table_name='student_writings')
    op.drop_table('student_writings')
    # ### end Alembic commands ###
