"""add_progress_fields

Revision ID: 87727891177f
Revises: f20c5293d56c
Create Date: 2026-07-15 17:48:01.523831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87727891177f'
down_revision: Union[str, Sequence[str], None] = 'f20c5293d56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('lesen_score', sa.Integer(), nullable=False))
    op.add_column('certificates', sa.Column('hoeren_score', sa.Integer(), nullable=False))
    op.add_column('certificates', sa.Column('schreiben_score', sa.Integer(), nullable=False))
    op.add_column('certificates', sa.Column('sprechen_score', sa.Integer(), nullable=False))
    op.add_column('certificates', sa.Column('issued_at', sa.DateTime(), nullable=False))
    op.add_column('payments', sa.Column('receipt_url', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'payments', ['transaction_id'])
    op.add_column('student_progress', sa.Column('module_completed', sa.Boolean(), nullable=False))
    op.add_column('student_progress', sa.Column('course_completed', sa.Boolean(), nullable=False))
    op.add_column('student_progress', sa.Column('unlocked', sa.Boolean(), nullable=False))
    op.add_column('student_progress', sa.Column('experience', sa.Integer(), nullable=False))
    op.add_column('student_progress', sa.Column('study_minutes', sa.Integer(), nullable=False))
    op.add_column('student_progress', sa.Column('streak_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_progress', 'streak_days')
    op.drop_column('student_progress', 'study_minutes')
    op.drop_column('student_progress', 'experience')
    op.drop_column('student_progress', 'unlocked')
    op.drop_column('student_progress', 'course_completed')
    op.drop_column('student_progress', 'module_completed')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'receipt_url')
    op.drop_column('certificates', 'issued_at')
    op.drop_column('certificates', 'sprechen_score')
    op.drop_column('certificates', 'schreiben_score')
    op.drop_column('certificates', 'hoeren_score')
    op.drop_column('certificates', 'lesen_score')
    # ### end Alembic commands ###
