"""create_speakings_table

Revision ID: 91184abc44ec
Revises: b6e917e8c4da
Create Date: 2026-07-12 16:53:29.549144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91184abc44ec'
down_revision: Union[str, Sequence[str], None] = 'b6e917e8c4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speakings',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('sample_answer', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('preparation_time', sa.Integer(), nullable=False),
    sa.Column('speaking_time', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakings_lesson_id'), 'speakings', ['lesson_id'], unique=False)
    op.create_table('student_speakings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('speaking_id', sa.UUID(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('grammar_score', sa.Integer(), nullable=False),
    sa.Column('vocabulary_score', sa.Integer(), nullable=False),
    sa.Column('pronunciation_score', sa.Integer(), nullable=False),
    sa.Column('fluency_score', sa.Integer(), nullable=False),
    sa.Column('task_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['speaking_id'], ['speakings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_speakings_speaking_id'), 'student_speakings', ['speaking_id'], unique=False)
    op.create_index(op.f('ix_student_speakings_user_id'), 'student_speakings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_speakings_user_id'), table_name='student_speakings')
    op.drop_index(op.f('ix_student_speakings_speaking_id'), table_name='student_speakings')
    op.drop_table('student_speakings')
    op.drop_index(op.f('ix_speakings_lesson_id'), table_name='speakings')
    op.drop_table('speakings')
    # ### end Alembic commands ###
