"""create reading questions

Revision ID: f2b261698efd
Revises: 4dc87a50ec32
Create Date: 2026-07-11 04:55:39.548261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b261698efd'
down_revision: Union[str, Sequence[str], None] = '4dc87a50ec32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_options',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['reading_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_options_question_id'), 'reading_options', ['question_id'], unique=False)
    op.drop_column('reading_questions', 'option_b')
    op.drop_column('reading_questions', 'option_c')
    op.drop_column('reading_questions', 'option_a')
    op.drop_column('reading_questions', 'correct_answer')
    op.drop_column('reading_questions', 'option_d')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_questions', sa.Column('option_d', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('reading_questions', sa.Column('correct_answer', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('reading_questions', sa.Column('option_a', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('reading_questions', sa.Column('option_c', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('reading_questions', sa.Column('option_b', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_reading_options_question_id'), table_name='reading_options')
    op.drop_table('reading_options')
    # ### end Alembic commands ###
